### ISSUE TITLE
range already mapped assert with page-crossing instruction fetches

### ISSUE THREAD

**Issue by quic-egmc** [Minres/DBT-RISE-RISCV#10]
I'm hitting an edge case in DMI that results in an assert in the range_lut from the dmi_lut.addEntry call in core_complex.cpp.

The instruction fetch is trying to do a 4-byte read from 0x1bb02ffe. The get_direct_mem_ptr returns a DMI range:
```
start: 0x1bb02000
  end: 0x1bb02fff
```

as you can see the DMI page size is 4KB. The memory model DMI page size is actually larger but there's an interconnect component that narrows it down.

When core_complex attempts the dmi_lut.addEntry call it fails due to this assert:
```
 if(iter != m_lut.end() && iter->second.index != null_entry)
        throw std::runtime_error("range already mapped");
```

The earlier check for "is this already mapped?" is considering both start and end address and since the previous LUT entry does not cover the whole range, this if statement is not true:
```
if(lut_entry.get_granted_access() != tlm::tlm_dmi::DMI_ACCESS_NONE && addr + length <= lut_entry.get_end_address() + 1) {
```

So I think we either need to guarantee that all instruction fetches are naturally aligned (with the assumption that DMI granularity is sufficiently large for all naturally aligned fetches) OR we need to handle page boundary crossing in the instruction fetch logic.

**Comment by eyck** [comment]
@quic-egmc Could you give the patch a try? At least it does not try to add the entry if the access does not fit into the dmi range. So you will get 1x get_direct_mem_ptr() call whose return value is just dropped in this edge case.
If this leads to a significant performance impact we can extend the dmi handling to fetch consecutive pages.

**Comment by quic-egmc** [comment]
Code review: this looks good and pretty low risk.  Since this is only for these rare cases of having an instruction cross a DMI page boundary (which was taking me 800k instructions to reach the first instance).

I've tested this but my software image layout changed a little bit and no longer induces this condition - I'll try to get it back into this state to give a proper test.

**Comment by quic-egmc** [comment]
Ok, I managed to get my software image put back, reproduced the condition and can confirm the fix works.

Thanks for the quick turnaround @eyck !
